[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor --chip esp32s3 --log-format defmt"
# runner = "probe-rs run --chip esp32s3"

[env]
DEFMT_LOG="info"

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
]

target = "xtensa-esp32s3-espidf" #"xtensa-esp32s3-none-elf"

[unstable]
build-std = ["alloc", "core"]
